---
- name: Deploy daoistic
  hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  vars:

      daoistic_repo: https://github.com/tessercat/daoistic-web.git
      daoistic_version: master

      book_repo: https://github.com/tessercat/daoistic-book.git
      book_version: master

  roles:
      - {role: daoistic, tags: [daoistic]}
