---

# Handle app config notifications.

- name: Update venv
  listen:
      - configure daoistic venv
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/pip install --upgrade pip pip-tools

- name: Configure venv requirements
  listen:
      - configure daoistic venv
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/pip-sync requirements.txt
  args:
      chdir: /opt/daoistic

- name: Migrate db
  listen:
      - migrate daoistic db
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py migrate
  args:
      chdir: /opt/daoistic

- name: Create project admin user
  listen:
      - create daoistic admin user
  become: yes
  become_user: "{{ daoistic_user }}"
  command: "/opt/daoistic/var/venv/bin/python manage.py createadminuser {{ daoistic_admin_password }}"
  args:
      chdir: /opt/daoistic

- name: Import Unihan data
  listen:
      - import daoistic unihan data
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py importunihan
  args:
      chdir: /opt/daoistic

- name: Import book data
  listen:
      - import daoistic book data
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py importdaoistic
  args:
      chdir: /opt/daoistic

- name: Import blog data
  listen:
      - import daoistic blog data
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py importblog
  args:
      chdir: /opt/daoistic

# Handle service config notifications.

- name: Run systemd-tmpfiles
  listen:
      - run daoistic systemd-tmpfiles
  command: /bin/systemd-tmpfiles --create daoistic.conf

- name: Restart socket
  listen:
      - restart daoistic socket
  systemd:
      name: daoistic.socket
      enabled: yes
      daemon-reload: yes
      state: restarted

- name: Restart service
  listen:
      - restart daoistic service
  systemd:
      name: daoistic.service
      daemon-reload: yes
      state: restarted

- name: Restart nginx service
  listen:
      - restart daoistic nginx service
  systemd:
      name: nginx.service
      state: restarted
