---
- name: Install packages
  apt:
      name: "{{ packages }}"
  vars:
      packages:
          - build-essential
          - git
          - memcached
          - python3-dev
          - python3-venv

- name: Configure user
  user:
      name: "{{ daoistic_user }}"
      shell: /bin/bash

# Configure app.

- name: Configure directory
  file:
      path: /opt/daoistic
      state: directory
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"
      mode: 0755

- name: Clone repo
  notify:
      - configure daoistic venv
      - migrate daoistic db
      - restart daoistic service
  become: yes
  become_user: "{{ daoistic_user }}"
  git:
      repo: "git://localhost:9418/daoistic-web.git"
      dest: /opt/daoistic
      version: master
      force: yes

- name: Create venv
  notify:
      - configure daoistic venv
      - restart daoistic service
  become: yes
  become_user: "{{ daoistic_user }}"
  command: python3 -m venv venv
  args:
      chdir: /opt/daoistic/var
      creates: /opt/daoistic/var/venv

- name: Configure settings
  notify:
      - restart daoistic service
  become: yes
  become_user: "{{ daoistic_user }}"
  template:
      src: settings.py.j2
      dest: /opt/daoistic/var/settings.py
      mode: 0600

# Configure app services.

- name: Configure run directory
  notify:
      - run daoistic systemd-tmpfiles
  template:
      src: daoistic.tmpfile
      dest: /etc/tmpfiles.d/daoistic.conf
      mode: 0644

- name: Configure socket
  notify:
      - restart daoistic socket
  copy:
      src: daoistic.socket
      dest: /etc/systemd/system/daoistic.socket
      mode: 0644

- name: Configure service
  notify:
      - restart daoistic service
  template:
      src: daoistic.service
      dest: /etc/systemd/system/daoistic.service
      mode: 0644

# Configure nginx to serve the app.

- name: Configure HTTP server
  notify:
      - restart daoistic nginx service
  template:
      src: daoistic-http.conf.j2
      dest: /etc/nginx/conf.d/daoistic-http.conf
      mode: 0644

- name: Configure HTTPS server
  notify:
      - restart daoistic nginx service
  template:
      src: daoistic-https.conf.j2
      dest: /etc/nginx/conf.d/daoistic-https.conf
      mode: 0644

# Configure daoistic data.

- name: Create link to Unihan data
  file:
      src: "{{ playbook_dir }}/host_data/unihan12.tgz"
      dest: "{{ playbook_dir }}/roles/daoistic/deploy/files/unihan.tgz"
      state: link
  delegate_to: localhost

- name: Copy Unihan data
  unarchive:
      src: unihan.tgz
      dest: /opt/daoistic/var
      creates: /opt/daoistic/var/unihan
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"

- name: Copy book data
  unarchive:
      src: "{{ inventory_hostname }}.book.tgz"
      dest: /opt/daoistic/var
      creates: /opt/daoistic/var/book
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"

# Check app db and notify handlers based on db state.

- name: Stat db
  stat:
      path: /opt/daoistic/var/db.sqlite3
  register: stat_daoistic_db

- name: Notify migration handler
  notify:
      - migrate daoistic db
  command: /bin/true
  when: not stat_daoistic_db.stat.exists

- name: Notify admin user handler
  notify:
      - create daoistic admin user
  command: /bin/true
  when: not stat_daoistic_db.stat.exists

- name: Notify Unihan data handler
  notify:
      - import daoistic unihan data
  command: /bin/true
  when: not stat_daoistic_db.stat.exists

- name: Notify book data handler
  notify:
      - import daoistic book data
      - import daoistic blog data
  command: /bin/true
  when: not stat_daoistic_db.stat.exists

# And finally.

- name: Run handlers
  meta: flush_handlers
