---
- name: Export book data
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py exportdaoistic
  args:
      chdir: /opt/daoistic

- name: Archive directory
  command: tar -C /opt/daoistic/var -czvf /tmp/daoistic.tgz book warn=no

- name: Fetch archive
  fetch:
      src: /tmp/daoistic.tgz
      dest: "host_data/{{ inventory_hostname }}/{{ ansible_date_time.date }}.daoistic.tgz"
      flat: yes

- name: Remove archive from remote host
  file:
      path: /tmp/daoistic.tgz
      state: absent

- name: Create link to unihan data
  file:
      src: "{{ playbook_dir }}/host_data/unihan12.tgz"
      dest: "{{ playbook_dir }}/roles/daoistic/deploy/files/unihan.tgz"
      state: link
  delegate_to: localhost

- name: Create backup link to book data
  file:
      src: "{{ playbook_dir }}/host_data/{{ inventory_hostname }}/{{ ansible_date_time.date }}.daoistic.tgz"
      dest: "{{ playbook_dir }}/roles/daoistic/deploy/files/{{ inventory_hostname }}/daoistic.tgz"
      state: link
  delegate_to: localhost
