---
- name: Restart socket
  listen:
      - restart daoistic socket
  systemd:
      name: daoistic.socket
      state: restarted

- name: Restart service
  listen:
      - restart daoistic service
  systemd:
      name: daoistic.service
      state: restarted

- name: Restart nginx service
  listen:
      - restart daoistic nginx service
  systemd:
      name: nginx.service
      state: restarted
