---

# OS.

- name: Packages
  apt:
      name: "{{ packages }}"
  vars:
      packages:
          - build-essential
          - git
          - memcached
          - python3-dev
          - python3-venv

- name: User
  user:
      name: "{{ daoistic_user }}"
      shell: /bin/bash


# Django project.

- name: Deployment directory
  file:
      path: /opt/daoistic
      state: directory
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"
      mode: 0755

- name: Directory
  file:
      path: /opt/daoistic/web
      state: directory
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"
      mode: 0700

- name: Repo
  notify:
      - restart daoistic service
  become: true
  become_user: "{{ daoistic_user }}"
  git:
      repo: "git://localhost:{{ ansible_gitd_port }}/daoistic/web.git"
      dest: /opt/daoistic
      version: master
      force: true
  register: daoistic_repo
  # Clean
  # Upgrade
  # Requirements
  # Migrate

- name: Clean
  file:
      path: /opt/daoistic/static
      state: absent
  when: daoistic_repo is changed

- name: Stat static
  stat:
      path: /opt/daoistic/static
  register: daoistic_static
  # Static.

- name: Static
  copy:
      src: /opt/daoistic/web/static
      dest: /opt/daoistic
      remote_src: true
      owner: www-data
      group: www-data
      mode: 0700
  when: not daoistic_static.stat.exists

- name: Settings
  notify:
      - restart daoistic service
  become: true
  become_user: "{{ daoistic_user }}"
  template:
      src: settings.py
      dest: /opt/daoistic/web/var/settings.py

- name: Link Unihan
  file:
      src: "{{ playbook_dir }}/host_data/unihan12.tgz"
      dest: "{{ playbook_dir }}/roles/daoistic/web/deploy/files/unihan.tgz"
      state: link
  delegate_to: localhost

- name: Unarchive Unihan
  unarchive:
      src: unihan.tgz
      dest: /opt/daoistic/web/var
      creates: /opt/daoistic/web/var/unihan
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"
  register: daoistic_unihan
  # Import unihan

- name: Unarchive book
  unarchive:
      src: "{{ inventory_hostname }}.book.tgz"
      dest: /opt/daoistic/web/var
      creates: /opt/daoistic/web/var/book
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"
  register: daoistic_book
  # Import book
  # Import blog


# Venv.

- name: Venv
  notify:
      - restart daoistic service
  become: true
  become_user: "{{ daoistic_user }}"
  command: python3 -m venv venv
  args:
      chdir: /opt/daoistic/web/var
      creates: /opt/daoistic/web/var/venv
  register: daoistic_venv
  # Upgrade
  # Requirements

- name: Upgrade
  become: true
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/web/var/venv/bin/pip install --upgrade pip pip-tools
  when: daoistic_repo is changed or daoistic_venv is changed

- name: Requirements
  become: true
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/web/var/venv/bin/pip-sync requirements.txt
  args:
      chdir: /opt/daoistic/web
  when: daoistic_repo is changed or daoistic_venv is changed


# Maintenance commands.

- name: Stat db
  stat:
      path: /opt/daoistic/web/var/db.sqlite3
  register: daoistic_db
  # Migrate
  # Admin user

- name: Migrate
  become: true
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/web/var/venv/bin/python manage.py migrate
  args:
      chdir: /opt/daoistic/web
  when: daoistic_repo is changed or not daoistic_db.stat.exists

- name: Admin user
  become: true
  become_user: "{{ daoistic_user }}"
  command: "/opt/daoistic/web/var/venv/bin/python manage.py \
            createadminuser {{ daoistic_admin_password }}"
  args:
      chdir: /opt/daoistic/web
  when: not daoistic_db.stat.exists

- name: Import Unihan
  become: true
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/web/var/venv/bin/python manage.py importunihan
  args:
      chdir: /opt/daoistic/web
  when: daoistic_unihan is changed

- name: Import book
  become: true
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/web/var/venv/bin/python manage.py importbook
  args:
      chdir: /opt/daoistic/web
  when: daoistic_book is changed

- name: Import blog
  become: true
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/web/var/venv/bin/python manage.py importblog
  args:
      chdir: /opt/daoistic/web
  when: daoistic_book is changed


# Systemd tmpfiles.

- name: Run directory
  template:
      src: tmpfile
      dest: /etc/tmpfiles.d/daoistic.conf
      mode: 0644

- name: Stat directory
  stat:
      path: /run/daoistic
  register: daoistic_tmpfile
  # Systemd-tmpfiles

- name: Systemd-tmpfiles
  command: /bin/systemd-tmpfiles --create daoistic.conf
  when: not daoistic_tmpfile.stat.exists


# Systemd service.

- name: Socket file
  notify:
      - restart daoistic socket
  copy:
      src: socket
      dest: /etc/systemd/system/daoistic.socket
      mode: 0644

- name: Socket status
  systemd:
      name: daoistic.socket
      enabled: true
      daemon-reload: true

- name: Service file
  notify:
      - restart daoistic service
  template:
      src: service
      dest: /etc/systemd/system/daoistic.service
      mode: 0644

- name: Service status
  systemd:
      name: daoistic.service
      enabled: true
      daemon-reload: true


# Nginx servers.

- name: HTTP server
  notify:
      - restart daoistic nginx service
  template:
      src: http.conf
      dest: /etc/nginx/conf.d/daoistic-http.conf
      mode: 0644

- name: HTTPS server
  notify:
      - restart daoistic nginx service
  template:
      src: https.conf
      dest: /etc/nginx/conf.d/daoistic-https.conf
      mode: 0644


# Handlers.

- name: Handlers
  meta: flush_handlers
