---

# OS.

- name: Packages
  apt:
      pkg:
          - git
          - memcached
          - python3-venv


# Django project.

- name: Deployment directory
  file:
      path: /opt/daoistic
      state: directory
      owner: peter
      group: peter
      mode: 0755

- name: Directory
  file:
      path: /opt/daoistic/web
      state: directory
      owner: peter
      group: peter
      mode: 0700

- name: Repo
  notify:
      - restart daoistic service
  become: true
  become_user: peter
  git:
      repo: "{{ daoistic_repo }}"
      dest: /opt/daoistic/web
      version: "{{ daoistic_version }}"
      force: true
  register: daoistic_git
  # Clean
  # Upgrade
  # Requirements
  # Migrate

- name: Clean
  file:
      path: /opt/daoistic/static
      state: absent
  when: daoistic_git is changed

- name: Stat static
  stat:
      path: /opt/daoistic/static
  register: daoistic_static
  # Static.

- name: Static
  copy:
      src: /opt/daoistic/web/static
      dest: /opt/daoistic
      remote_src: true
      owner: www-data
      group: www-data
      mode: 0700
  when: not daoistic_static.stat.exists

- name: Settings
  notify:
      - restart daoistic service
  become: true
  become_user: peter
  template:
      src: settings.py
      dest: /opt/daoistic/web/var/settings.py

- name: Copy Unihan
  copy:
      src: /opt/ansible/unihan
      dest: /opt/daoistic/web/var/
      owner: peter
      group: peter
  register: daoistic_unihan
  # Import unihan

- name: Stat book
  stat:
      path: /opt/daoistic/web/var/book
  register: daoistic_book_dir
  # Book

- name: Book
  become: true
  become_user: peter
  git:
      repo: "{{ book_repo }}"
      dest: /opt/daoistic/web/var/book
      version: "{{ book_version }}"
  register: daoistic_book
  when: not daoistic_book_dir.stat.exists
  # Import book
  # Import blog


# Venv.

- name: Venv
  notify:
      - restart daoistic service
  become: true
  become_user: peter
  command: python3 -m venv venv
  args:
      chdir: /opt/daoistic/web/var
      creates: /opt/daoistic/web/var/venv
  register: daoistic_venv
  # Upgrade
  # Requirements

- name: Upgrade
  become: true
  become_user: peter
  command: /opt/daoistic/web/var/venv/bin/pip install --upgrade pip pip-tools
  when: daoistic_git is changed or daoistic_venv is changed

- name: Requirements
  become: true
  become_user: peter
  command: /opt/daoistic/web/var/venv/bin/pip-sync requirements.txt
  args:
      chdir: /opt/daoistic/web
  when: daoistic_git is changed or daoistic_venv is changed


# Management commands.

- name: Stat db
  stat:
      path: /opt/daoistic/web/var/db.sqlite3
  register: daoistic_db
  # Migrate
  # Admin user

- name: Migrate
  become: true
  become_user: peter
  command: /opt/daoistic/web/var/venv/bin/python manage.py migrate
  args:
      chdir: /opt/daoistic/web
  when: daoistic_git is changed or not daoistic_db.stat.exists

- name: Import Unihan
  become: true
  become_user: peter
  command: /opt/daoistic/web/var/venv/bin/python manage.py importunihan
  args:
      chdir: /opt/daoistic/web
  when: daoistic_unihan is changed

- name: Import book
  become: true
  become_user: peter
  command: /opt/daoistic/web/var/venv/bin/python manage.py importchapter --chapter all
  args:
      chdir: /opt/daoistic/web
  when: daoistic_book is changed

- name: Import ctext
  become: true
  become_user: peter
  command: /opt/daoistic/web/var/venv/bin/python manage.py importctext
  args:
      chdir: /opt/daoistic/web
  when: daoistic_book is changed

- name: Import blog
  become: true
  become_user: peter
  command: /opt/daoistic/web/var/venv/bin/python manage.py importblog
  args:
      chdir: /opt/daoistic/web
  when: daoistic_book is changed


# Systemd tmpfiles.

- name: Run directory
  copy:
      src: tmpfile
      dest: /etc/tmpfiles.d/daoistic.conf
      mode: 0644

- name: Stat directory
  stat:
      path: /run/daoistic
  register: daoistic_tmpfile
  # Systemd-tmpfiles

- name: Systemd-tmpfiles
  command: /bin/systemd-tmpfiles --create daoistic.conf
  when: not daoistic_tmpfile.stat.exists


# Systemd service.

- name: Service file
  notify:
      - restart daoistic service
  copy:
      src: service
      dest: /etc/systemd/system/daoistic.service
      mode: 0644

- name: Service status
  systemd:
      name: daoistic.service
      enabled: true
      daemon-reload: true


# Nginx servers.

- name: HTTP server
  notify:
      - restart daoistic nginx service
  template:
      src: http.conf
      dest: /etc/nginx/conf.d/daoistic-http.conf
      mode: 0644

- name: HTTPS server
  notify:
      - restart daoistic nginx service
  template:
      src: https.conf
      dest: /etc/nginx/conf.d/daoistic-https.conf
      mode: 0644


# Handlers.

- name: Handlers
  meta: flush_handlers
