---

# OS.

- name: Packages
  apt:
      name: "{{ packages }}"
  vars:
      packages:
          - build-essential
          - git
          - memcached
          - python3-dev
          - python3-venv

- name: User
  user:
      name: "{{ daoistic_user }}"
      shell: /bin/bash


# Django project.

- name: Directory
  file:
      path: /opt/daoistic
      state: directory
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"
      mode: 0755

- name: Repo
  notify:
      - restart daoistic service
  become: yes
  become_user: "{{ daoistic_user }}"
  git:
      repo: "git://localhost:{{ ansible_gitd_port }}/daoistic/web.git"
      dest: /opt/daoistic
      version: master
      force: yes
  register: daoistic_repo
  # Init venv
  # Migrate

- name: Settings
  notify:
      - restart daoistic service
  become: yes
  become_user: "{{ daoistic_user }}"
  template:
      src: settings.py.j2
      dest: /opt/daoistic/var/settings.py
      mode: 0600
  register: daoistic_settings
  # Init venv

- name: Link Unihan
  file:
      src: "{{ playbook_dir }}/host_data/unihan12.tgz"
      dest: "{{ playbook_dir }}/roles/daoistic/web/deploy/files/unihan.tgz"
      state: link
  delegate_to: localhost

- name: Unarchive
  unarchive:
      src: unihan.tgz
      dest: /opt/daoistic/var
      creates: /opt/daoistic/var/unihan
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"
  register: daoistic_unihan
  # Import unihan

- name: Book
  unarchive:
      src: "{{ inventory_hostname }}.book.tgz"
      dest: /opt/daoistic/var
      creates: /opt/daoistic/var/book
      owner: "{{ daoistic_user }}"
      group: "{{ daoistic_user }}"
  register: daoistic_book
  # Import book


# Venv.

- name: Venv
  notify:
      - restart daoistic service
  become: yes
  become_user: "{{ daoistic_user }}"
  command: python3 -m venv venv
  args:
      chdir: /opt/daoistic/var
      creates: /opt/daoistic/var/venv
  register: daoistic_venv
  # Init venv

- name: Upgrade
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/pip install --upgrade pip pip-tools
  when: daoistic_repo is changed or daoistic_venv is changed

- name: Requirements
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/pip-sync requirements.txt
  args:
      chdir: /opt/daoistic
  when: daoistic_repo is changed or daoistic_venv is changed


# Maintenance commands.

- name: Stat db
  stat:
      path: /opt/daoistic/var/db.sqlite3
  register: daoistic_db

- name: Migrate
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py migrate
  args:
      chdir: /opt/daoistic
  when: not daoistic_db.stat.exists or daoistic_repo is changed

- name: Admin user
  become: yes
  become_user: "{{ daoistic_user }}"
  when: not daoistic_db.stat.exists
  command: "/opt/daoistic/var/venv/bin/python manage.py createadminuser {{ daoistic_admin_password }}"
  args:
      chdir: /opt/daoistic
  when: not daoistic_db.stat.exists

- name: Import Unihan
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py importunihan
  args:
      chdir: /opt/daoistic
  when: daoistic_unihan is changed

- name: Import book
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py importbook
  args:
      chdir: /opt/daoistic
  when: daoistic_book is changed

- name: Import blog
  become: yes
  become_user: "{{ daoistic_user }}"
  command: /opt/daoistic/var/venv/bin/python manage.py importblog
  args:
      chdir: /opt/daoistic
  when: daoistic_book is changed


# Systemd tmpfiles.

- name: Run directory
  template:
      src: daoistic.tmpfile
      dest: /etc/tmpfiles.d/daoistic.conf
      mode: 0644

- name: Stat directory
  stat:
      path: /run/daoistic
  register: daoistic_tmpfile
  # Systemd-tmpfiles

- name: Systemd-tmpfiles
  command: /bin/systemd-tmpfiles --create daoistic.conf
  when: not daoistic_tmpfile.stat.exists


# Systemd service.

- name: Socket file
  notify:
      - restart daoistic socket
  copy:
      src: daoistic.socket
      dest: /etc/systemd/system/daoistic.socket
      mode: 0644

- name: Socket status
  systemd:
      name: daoistic.socket
      enabled: yes
      daemon-reload: yes

- name: Service file
  notify:
      - restart daoistic service
  template:
      src: daoistic.service
      dest: /etc/systemd/system/daoistic.service
      mode: 0644

- name: Service status
  systemd:
      name: daoistic.service
      enabled: yes
      daemon-reload: yes


# Nginx servers.

- name: HTTP server
  notify:
      - restart daoistic nginx service
  template:
      src: daoistic-http.conf.j2
      dest: /etc/nginx/conf.d/daoistic-http.conf
      mode: 0644

- name: HTTPS server
  notify:
      - restart daoistic nginx service
  template:
      src: daoistic-https.conf.j2
      dest: /etc/nginx/conf.d/daoistic-https.conf
      mode: 0644


# Handlers.

- name: Handlers
  meta: flush_handlers
